# Generated by Django 2.2.24 on 2023-07-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='LinkStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Простая ссылка')),
                ('bitlink', models.CharField(blank=True, max_length=200, verbose_name='Bitly ссылка')),
                ('description', models.TextField(verbose_name='Описание ссылки')),
                ('transitions', models.IntegerField(default=0, verbose_name='Количество переходов по ссылке')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата участника')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя участника')),
            ],
        ),
        migrations.CreateModel(
            name='CakeConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_level', models.CharField(choices=[('one', '1 уровень'), ('two', '2 уровня'), ('three', '3 уровня')], default='one', max_length=5, verbose_name='Количество уровней торта')),
                ('base_of_cake', models.CharField(choices=[('vanila', 'Ванильный бисквит'), ('choco', 'Шоколадный бисквит'), ('marble', 'Мраморный бисквит')], default='vanila', max_length=6, verbose_name='Основа для торта')),
                ('topping', models.CharField(blank=True, choices=[('wedge', 'Клиновый сироп'), ('caramel', 'Карамельный сироп')], max_length=7, verbose_name='Топпинг')),
                ('blackberry', models.BooleanField(default=False, verbose_name='Еживика')),
                ('raspberry', models.BooleanField(default=False, verbose_name='Малина')),
                ('blueberry', models.BooleanField(default=False, verbose_name='Голубика')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.Member', verbose_name='Заказчик')),
            ],
        ),
    ]
