# Generated by Django 2.2.24 on 2023-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeconstructor',
            name='strawberry',
            field=models.BooleanField(default=False, verbose_name='Клубника'),
        ),
        migrations.AlterField(
            model_name='cakeconstructor',
            name='topping',
            field=models.CharField(blank=True, choices=[('wedge', 'Клиновый сироп'), ('caramel', 'Карамельный сироп'), ('milk_choco', 'Молочный шоколад'), ('blueberry_syrup', 'Черничный сироп')], max_length=7, verbose_name='Топпинг'),
        ),
    ]
